### ISSUE TITLE
Thresholds color filter not preserved during 3.2 -> 3.3 upgrade, resulting in a different view on upgrade

### ISSUE THREAD

**Issue by vishalnandagopal** [VolkovLabs/business-calendar#245]
I have many dashboards on the v3.2.0 of the plugin which pick the color for the event based on a threshold value.

1. Current environmental details:
a. Grafana v10.4
b. Business calendar v3.2.0

Example panel:
![image](https://github.com/user-attachments/assets/67286e36-e9c0-45cd-95c2-af72a3a1e32c)

Panel config:
<img src="https://github.com/user-attachments/assets/c42dcdba-21e2-4266-905b-c3820d3c0b58" width="400px">
<img src="https://github.com/user-attachments/assets/808c2b6c-23f4-40ff-aac8-adf2207294d9" width="400px">
<img src="https://github.com/user-attachments/assets/b7b23ae8-ceef-4f65-9bd2-0db19f1f0298" width="400px">
<img src="https://github.com/user-attachments/assets/348df5b6-bad1-401c-8fc2-221f0983be4d" width="400px">

2. Upgraded env
a. Grafana v10.4
b. Business calendar plugin v3.3.0

Same panel after upgrading:
![image](https://github.com/user-attachments/assets/c258c7fc-9885-40a1-869f-631e879b1aed)

Panel config (did not change anything after upgrading):
<img src="https://github.com/user-attachments/assets/85608a93-1d42-4b6d-b902-c75d462bc495" width="400px">
<img src="https://github.com/user-attachments/assets/b7b23ae8-ceef-4f65-9bd2-0db19f1f0298" width="400px">
<img src="https://github.com/user-attachments/assets/348df5b6-bad1-401c-8fc2-221f0983be4d" width="400px">

Although the option to change to thresholds is there, it is currently breaking older dashboards who are defaulting to "frame" now.

I am currently working on a PR to fix this, have created an issue to discuss and get feedback.

**Comment by vishalnandagopal** [comment]
The description of the "Colors" in layout is display based on frame/event if color field is not specified. So if color scheme -> thresholds by value is already defined, it should default to selecting colors > thresholds.

Is this an acceptable behaviour?

**Comment by mikhail-vl** [comment]
@vishalnandagopal Thank you for reporting an issue. The proposed behavior looks reasonable.

**Comment by vishalnandagopal** [comment]
Hi, I started working on a fix. I am setting colormode as threshold (TH) if the user has put value mappings for specific colors.

Current value: ColorMode.Frame and color mappings set as (Value1 -> Red, Value2 -> Yellow, etc)

I have written a line that checks

```
if colormode ='frame' && value mappings are set:
        set colormode = threshold
```

Another problem has popped up now. After I have set colormode as TH, if the user clicks on "Frame" and tries to set it, the code will ignore it and set colorMode to threshold again since the color mappings are still set. This happens like a loop and it is reflected on the UI, when color is changed to threshold as soon as user clicks on frame.

Do you have any suggestions to fix this issue @vitPinchuk ?

**Comment by mikhail-vl** [comment]
@vishalnandagopal It should be done using migrations.

  @vitPinchuk will update it after rBusiness Variables panel updates for Grafana 11.3.

**Comment by vishalnandagopal** [comment]
Thank you @mikhail-vl , @vitPinchuk for fixing this!

**Comment by mikhail-vl** [comment]
@vishalnandagopal Let us know if you spot any more issues.

**Comment by vishalnandagopal** [comment]
I have tested it. Upgraded directly from 2.5 to 3.9. The thresholds logic is working perfectly.

**Comment by mikhail-vl** [comment]
@vishalnandagopal Thank you for confirming.
